pipeline{
    agent any

    parameters{
        string(defaultValue: "Test", description: "Deployment name:", name:"deployName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], name: "AZname")
        booleanParam(defaultValue: false, description: "Confirm the action", name: "deployCheck")
}
    stages{
        stage("Demo"){
            steps{
                echo "Deployment name is: ${params.deployName}"
                echo "AZ name is: ${params.AZname}"
                echo "Deployment checkbox was secured as: ${params.deployCheck}"
            }
        }
    }
}